alias d="docker"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dr="docker run"
alias drm="docker rm"
alias drmi="docker rmi"
alias dimg="docker images"
alias dex="docker exec"
alias dst="docker stop"
alias dkl="docker kill"

alias dc="docker-compose"
alias dcu="docker-compose up"
alias dcd="docker-compose down"
