alias g='git'
alias gcl='git clone'
alias gi='git init'
alias gst='git status --short --branch --show-stash'
alias gd='git diff'
alias gds='git diff --staged'
alias gpl='git up'
alias gps='git push'
alias gpsh='git push --set-upstream origin HEAD'
alias gpsf='git push --force-with-lease'
alias gf='git fetch'
alias gl='git log'
alias gll='git log -1'
alias ga='git add'
alias gaf='git add -f'
alias gc='git commit --verbose'
alias gbr='git branch'
alias gco='git checkout'
alias gsh='git stash'
alias gshl='git stash list'
alias gsha='git stash apply'
alias gshp='git stash pop'
alias gre='git rebase'

alias dot='git --git-dir=$HOME/dotfiles --work-tree=$HOME'
