#!/usr/bin/env bash
#===============================================================================
#
#          FILE: i3network
#
#         USAGE: ./i3network
#
#   DESCRIPTION: Used by i3blocks to print the network information.
#
#        AUTHOR: tung beier
#       CREATED: 21 August 2019 20:00 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails


#---  GLOBAL VARIABLES  --------------------------------------------------------
readonly ETHERNET_INTERFACE=enp0s31f6
readonly WIRELESS_INTERFACE=wlp3s0


#---  FUNCTION  ----------------------------------------------------------------
#          NAME: _get_ethernet_status
#   DESCRIPTION: Print the current ethernet network status
#       RETURNS: The ethernet information
#-------------------------------------------------------------------------------
_get_ethernet_status() {
  local STATE=$(cat /sys/class/net/${ETHERNET_INTERFACE}/operstate)
  local TAG=" "
  local COLOR="red"

  local IP_ADDRESS=$(ip a | grep "${ETHERNET_INTERFACE}$" | awk '{ print $2 }')

  if [[ "$STATE" = "up" ]]; then
    COLOR="green"
    echo "<span fgcolor='${COLOR}'>${TAG} ${IP_ADDRESS}</span>"
  else
    echo "<span fgcolor='${COLOR}'>${TAG} ${STATE}</span>"
  fi
}


#---  FUNCTION  ----------------------------------------------------------------
#          NAME: _get_wireless_status
#   DESCRIPTION: Print the current wireless network status
#       RETURNS: The wireless information
#-------------------------------------------------------------------------------
_get_wireless_status() {
  local STATE=$(cat /sys/class/net/${WIRELESS_INTERFACE}/operstate)
  local TAG=""
  local IP_ADDRESS=$(ip a | grep "${WIRELESS_INTERFACE}$" | awk '{ print $2 }')

  if [[ "$STATE" = "up" ]]; then
    local QUALITY=$(grep "$WIRELESS_INTERFACE" /proc/net/wireless | awk '{ print int($3 * 100 / 70 - 1) }')
    local COLOR="green"
    if [[ $QUALITY -lt 75 ]]; then
      COLOR="orange"
    elif [[ $QUALITY -lt 45 ]]; then
      COLOR="yellow"
    elif [[ $QUALITY -lt 15 ]]; then
      COLOR="red"
    fi
    echo "<span fgcolor='$COLOR'>${TAG} ${QUALITY}% ${IP_ADDRESS}</span>"
  else
    echo "<span fgcolor='red'>${TAG} ${STATE}</span>"
  fi
}


#---  SCRIPT LOGIC  ------------------------------------------------------------
echo "$(_get_ethernet_status)  $(_get_wireless_status)"

