#!/usr/bin/env bash
#===============================================================================
#
#          FILE: i3separator
#
#         USAGE: ./i3separator
#
#   DESCRIPTION: Used by i3separator to print a separator between i3 blocks.
#
#        AUTHOR: tung beier
#       CREATED: 01 September 2019 17:00 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails


#---  SCRIPT LOGIC  ------------------------------------------------------------
echo "<span>   </span>"

