#!/usr/bin/env bash
#===============================================================================
#
#          FILE: i3volume
#
#         USAGE: ./i3volume
#
#   DESCRIPTION: Used by i3blocks to display the current sound level.
#
#        AUTHOR: tung beier
#       CREATED: 21 August 2019 20:17 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails


#---  SCRIPT LOGIC  ------------------------------------------------------------
if [[ "$#" -eq 1 ]]; then
  case $1 in
    up) amixer -q set Master 10%+ ;;
    down) amixer -q set Master 10%- ;;
  esac

  pkill -RTMIN+10 i3blocks
fi

volume=$(amixer get Master | grep % | awk '{print $4}' | sed 's/[^0-9]//g')
if [[ "$volume" -eq "0" ]]; then
  icon="🔇"
elif [[ "$volume" -gt "70" ]]; then
  icon="🔊"
elif [[ "$volume" -lt "35" ]]; then
  icon="🔈"
else
  icon="🔉"
fi

echo "<span color='white'>${icon} ${volume}%</span>"

