#!/usr/bin/env bash
#===============================================================================
#
#          FILE: order66
#
#         USAGE: ./order66
#
#   DESCRIPTION: Backup some folders and shutdown.
#
#  REQUIREMENTS: rsync
#        AUTHOR: tung beier
#       CREATED: 21 August 2019 20:42 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails


#---  SCRIPT LOGIC  ------------------------------------------------------------
IDEA_PATH="${RAM_DISK_PATH}/idea-system"

if [[ -d "$BACK_UP_PATH" ]]; then
  mkdir -pv $BACK_UP_PATH
fi

if [[ -d "$IDEA_PATH" ]]; then
  rsync -aAXPv --delete $IDEA_PATH $BACK_UP_PATH
fi

shutdown -h now

