#!/usr/bin/env bash

# Switch console and vim theme from dark to light and vice versa.

VIM_DIR="${HOME}/.config/theme"
TERMITE_DIR="${HOME}/.config/termite"
IS_DARK_VIM_THEME=`grep 'DARK' ${HOME}/.config/theme/vim_theme | wc -l`

if [ "${IS_DARK_VIM_THEME}" == "1" ]; then
    echo "Change to light theme"
    echo 'y' | cp ${VIM_DIR}/vim_theme_light ${VIM_DIR}/vim_theme
    echo 'y' | cp ${TERMITE_DIR}/config_light ${TERMITE_DIR}/config
else
    echo "Change to dark theme"
    echo 'y' | cp ${VIM_DIR}/vim_theme_dark ${VIM_DIR}/vim_theme
    echo 'y' | cp ${TERMITE_DIR}/config_dark ${TERMITE_DIR}/config
fi

