#!/usr/bin/env bash

idea="$HOME/backup/idea-system"
android="$HOME/backup/android-studio-system"
dest="$HOME/downloads/"

if [ -d ${idea} ]; then
    rsync -aAXPv --delete ${idea} ${dest}
fi

if [ -d ${android} ]; then
    rsync -aAXPv --delete ${android} ${dest}
fi

