#!/usr/bin/env bash

# ----- Variables -----
# branch name
name=$(git symbolic-ref --short HEAD)
# branch prefix, e.g. feature, bugfix, etc.
prefix=$(echo ${name} | cut -d '/' -f 1)
# branch suffix == description
suffix=$(echo ${name} | cut -d '/' -f 2)

# check regex
prefix_regex="^[develop|integration|release]"

# ----- Functions -----

# ----- Logic -----
if [[ ${prefix} =~ $prefix_regex ]]; then
    cat << END
    ---------------------------------------------
    |                                           |
    |     THIS BRANCH IS OFF LIMIT, STUPID!     |
    |                                           |
    ---------------------------------------------
END
    exit 1
fi

if [ ! -f .git/COMMIT_EDITMSG ]; then
    echo 'EDITMSG file does not exist. Exiting commit message preparation.'
    exit 0
fi

if [ -f .git/MERGE_MSG ]; then
    exit 0
fi

task=${suffix}
if [[ ${suffix} == *"_"* ]]; then
    task=$(echo ${suffix} | cut -d '_' -f 1)
fi

sed -i "1i [$task] " .git/COMMIT_EDITMSG
exit 0
